#!/usr/bin/env perl

use 5.010001;
use strict;
use warnings;
use FindBin '$Bin';

my $p1_t1 = '2011-04-05T00:00:00';
my $p1_t2 = '2011-06-08T23:59:59';

my $p2_t1 = '2011-06-09T00:00:00';
my $p2_t2 = '2011-11-19T23:59:59';

my $p3_t1 = '2011-11-20T00:00:00';
my $p3_t2 = '2013-11-30T23:59:59';

system "$Bin/../script/calc-returns '$p1_t1' '$p1_t2' --format csv > $Bin/../tmp/returns.p1.csv";
system "$Bin/../script/calc-returns '$p2_t1' '$p2_t2' --format csv > $Bin/../tmp/returns.p2.csv";
system "$Bin/../script/calc-returns '$p3_t1' '$p3_t2' --format csv > $Bin/../tmp/returns.p3.csv";
system "$Bin/../script/calc-returns '$p1_t1' '$p3_t2' --format csv > $Bin/../tmp/returns.p123.csv";
