#!/usr/bin/env perl

use 5.010001;
use strict;
use warnings;

use Data::Dump;
use DBIx::Connect::MySQL;
use Progress::Any '$progress';
use Progress::Any::Output 'TermProgressBarColor';

my $dbh = DBIx::Connect::MySQL->connect(
    "dbi:mysql:database=mtgox", undef, undef
);

my $row_where = " WHERE Currency__='CNY'";

$progress->target($dbh->selectrow_arrayref("SELECT COUNT(*) FROM Price$row_where")->[0]);

my $sth = $dbh->prepare("SELECT Price FROM Price$row_where");
$sth->execute;

my %digits;
while (my $row = $sth->fetchrow_hashref) {
    $progress->update;
    my ($piece) = sprintf("%.5f", $row->{Price}) =~ /\.(.+)/;
    warn "$row->{Price}\n" if !defined $piece;
    for (split //, $piece) {
        next unless /[0-9]/;
        $digits{$_}++;
    }
}

$progress->finish;

dd \%digits;

=head1 RESULT

=head2 CNY (sample too small, needs larger amount of price)

{
  "0" => 10672,
  "1" => 1685,
  "2" => 1671,
  "3" => 1631,
  "4" => 1569,
  "5" => 1657,
  "6" => 1601,
  "7" => 1686,
  "8" => 1695,
  "9" => 1668,
}

=head2 USD ()
