#!/usr/bin/env perl

use 5.010001;
use strict;
use warnings;
use FindBin '$Bin';
use Log::ger;
#use Log::ger::DBI::Query;

use DateTime;
use DBIx::Connect::MySQL;

my $dbh = DBIx::Connect::MySQL->connect(
    "dbi:mysql:database=mtgox", undef, undef, {RaiseError=>1});
$dbh->do("SET time_zone = '+00:00'");

$dbh->do("
CREATE TABLE IF NOT EXISTS _Daily_Price (
  Day INT NOT NULL PRIMARY KEY,
  Average DOUBLE NOT NULL,
  Lowest DOUBLE NOT NULL,
  Highest DOUBLE NOT NULL
) ENGINE='MyISAM';
");

my ($t1, $t2) = $dbh->selectrow_array(<<'_');
SELECT
  UNIX_TIMESTAMP(MIN(Stamp)), UNIX_TIMESTAMP(MAX(Stamp))
FROM _Trade2
_
my $dt1 = DateTime->from_epoch(epoch => $t1, time_zone=>'UTC');
my $dt1_bod = $dt1->clone; $dt1_bod->set(hour=>0, minute=>0, second=>0);
my $dt2 = DateTime->from_epoch(epoch => $t2, time_zone=>'UTC');

my $num_days = int(($dt2->epoch - $dt1_bod->epoch)/86400);

my %avg_prices;
my %lowest_prices;
my %highest_prices;
{
    my $sth;

    my %avg_prices_from_price_usd;
    my %highest_prices_from_price_usd;
    my %lowest_prices_from_price_usd;
    $sth = $dbh->prepare("SELECT Day,Average_Simple,Highest,Lowest FROM _Daily_Price_From_Price_Usd");
    $sth->execute;
    while (my @row = $sth->fetchrow_array) {
        $avg_prices_from_price_usd{$row[0]}     = $row[1];
        $highest_prices_from_price_usd{$row[0]} = $row[2];
        $lowest_prices_from_price_usd{$row[0]}  = $row[3];
    }

    my %avg_prices_from_price_jpy;
    my %highest_prices_from_price_jpy;
    my %lowest_prices_from_price_jpy;
    $sth = $dbh->prepare("SELECT Day,Average_Simple,Highest,Lowest FROM _Daily_Price_From_Price_Jpy");
    $sth->execute;
    while (my @row = $sth->fetchrow_array) {
        $avg_prices_from_price_jpy{$row[0]}     = $row[1];
        $highest_prices_from_price_jpy{$row[0]} = $row[2];
        $lowest_prices_from_price_jpy{$row[0]}  = $row[3];
    }

    my %avg_prices_from_trade2;
    my %highest_prices_from_trade2;
    my %lowest_prices_from_trade2;
    $sth = $dbh->prepare("SELECT Day,Average_Weighted,Highest,Lowest FROM _Daily_Price_From_Trade2");
    $sth->execute;
    while (my @row = $sth->fetchrow_array) {
        $avg_prices_from_trade2{$row[0]}     = $row[1];
        $highest_prices_from_trade2{$row[0]} = $row[2];
        $lowest_prices_from_trade2{$row[0]}  = $row[3];
    }

    for my $day (-1..$num_days+1) {

        my $avg = $avg_prices_from_price_usd{$day} //
            $avg_prices_from_price_jpy{$day} //
            $avg_prices_from_trade2{$day};
        unless (defined $avg) {
            warn "There is no price data for day $day";
            $avg = $avg_prices{ $day-1 };
            defined $avg or die;
        }
        $avg_prices{$day} = $avg;

        my $highest = $highest_prices_from_price_usd{$day} //
            $highest_prices_from_price_jpy{$day} //
            $highest_prices_from_trade2{$day};
        unless (defined $highest) {
            $highest = $highest_prices{ $day-1 };
            defined $highest or die;
        }
        $highest_prices{$day} = $highest;

        my $lowest = $lowest_prices_from_price_usd{$day} //
            $lowest_prices_from_price_jpy{$day} //
            $lowest_prices_from_trade2{$day};
        unless (defined $lowest) {
            $lowest = $lowest_prices{ $day-1 };
            defined $lowest or die;
        }
        $lowest_prices{$day} = $lowest;

        $dbh->do("INSERT INTO _Daily_Price (Day,Average,Lowest,Highest) VALUES (?,?,?,?)", {},
                 $day, $avg, $lowest, $highest);
    }

} # getting daily price data
