#!/usr/bin/env perl

# before running this script, you need to have already run gen-survival script
# first.

use 5.010001;
use strict;
use warnings;

use DBIx::Connect::MySQL;
my $dbh = DBIx::Connect::MySQL->connect(
    "dbi:mysql:database=mtgox", undef, undef, {RaiseError=>1});
$dbh->do("SET time_zone = '+00:00'");

$ARGV[0] or die "Usage: $0 <period>\n";

my $period = $dbh->selectrow_hashref("SELECT * FROM _Period WHERE Name=?", {}, $ARGV[0]);
$period or die "No such period '$ARGV[0]'\n";

my %users; # key=Index, value=1
my $sth = $dbh->prepare("SELECT DISTINCT `Index` FROM _Round_Trip WHERE Last_Tx_Stamp BETWEEN '$period->{Begin_Stamp}' AND '$period->{End_Stamp}'");
$sth->execute;
while (my $row = $sth->fetchrow_hashref) {
    $users{ $row->{Index} } = 1;
}

say "Day\tIndex\tSold\tTLI\tTGI";
for my $idx (sort {$a<=>$b} keys %users) {
    $sth = $dbh->prepare("SELECT Day, `Index`, Sold, TLI, TGI FROM _Survival WHERE `Index`=$idx AND Day BETWEEN $period->{Begin_Day} AND $period->{End_Day} ORDER BY Day");
    $sth->execute;
    while (my $row = $sth->fetchrow_arrayref) {
        say join("\t", @$row);
    }
}
